apiVersion: v1
kind: Service
metadata:
  name: php-my-admin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  selector:
    app: php-my-admin
  ports:
  - protocol: TCP
    name: pma
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-my-admin-deployment
  labels:
    app: php-my-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-my-admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-my-admin
    spec:
      containers:
      - name: php-my-admin
        image: php_my_admin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000